version: "3"

volumes:
  uluru-postgres-data:
    driver: local

services:
  #
  # POSTGRES
  #
  uluru-postgres:
    container_name: uluru-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - uluru-postgres-data:/var/lib/postgresql/data

  #
  # REDIS
  #
  uluru-redis:
    image: redis
    ports:
      - 6379:6379
  #
  # API
  #
  uluru-api:
    image: cagodoy/uluru-api:0.0.23
    ports:
      - 5000:5000
      - 5010:5010
      - 5020:5020
      - 5030:5030
    environment:
      - HOST=uluru-api
      - PORT=5000
      - ENVIRONMENT=development
      - DATABASE_URL=postgres://postgres:postgres@uluru-postgres:5432/postgres?sslmode=disable
      - JWT_SECRET=mega-secret
      - USERS_HOST=uluru-api
      - USERS_PORT=5020
      - AUTH_HOST=uluru-api
      - AUTH_PORT=5010
      - EMAIL_HOST=uluru-api
      - EMAIL_PORT=5030
      - REDIS_URL=redis://uluru-redis:6379/0
      - PROVIDERS=sendgrid
      - PROVIDER_SENDGRID_API_KEY=123
    depends_on:
      - uluru-postgres
    links:
      - uluru-postgres
