version: "3"

volumes:
  uluru-postgres-data:
    driver: local

services:
  #
  # POSTGRES
  #
  uluru-postgres:
    container_name: uluru-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - uluru-postgres-data:/var/lib/postgresql/data

  #
  # REDIS
  #
  uluru-redis:
    image: redis
    ports:
      - 6379:6379
  #
  # API
  #
  # uluru-api:
  #   container_name: uluru-api
  #   build: .
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  #     - PORT=5000
  #   depends_on:
  #     - uluru-postgres
  #   links:
  #     - uluru-postgres
